### ISSUE TITLE
Add "Open Opportunties" to DigitalGov logo

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas-open-opportunities#2]
The text should read "Open Opportunities for DigitalGov"

the logos that we use in the header are here:  https://github.com/18F/midas-open-opportunities/tree/master/assets/images
* ```logo.png```
* ```logo@2x.png```

(Note: logo_large.png is checked in so we have high resolution source, but it isn't currently used in the product)

Here are the three DigitalGov variants:

![image](https://cloud.githubusercontent.com/assets/41906/4926381/fdc3b600-6532-11e4-8ed8-d6a335719ee3.png)

![image](https://cloud.githubusercontent.com/assets/41906/4926367/e96a22fc-6532-11e4-9cf3-c7ad182914a5.png)

![image](https://cloud.githubusercontent.com/assets/41906/4926375/f63026c6-6532-11e4-832c-df8938c33ac2.png)

**Comment by dhcole** [comment]
Looks like this was completed.
