### ISSUE TITLE
As a new visitor, I should see a home page which leads me to click into the site

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas-open-opportunities#28]
Plan to mock up a few different directions, get reactions from users, then choose....

ideas:
- simple color block (like github home page), other photos
- call-to-action could be to explore opportunites (could leave same words, or try new words)

learning more (maybe this is when you scroll down):
- stories: see [hacking gov blog post](http://www.digitalgov.gov/2014/06/23/hacking-the-bureaucracy-one-task-at-a-time/) and hope to get some from user research: https://github.com/18F/midas-open-opportunities/issues/29
- promotional projects:  we should use data from [current Open Opportunities](http://gsablogs.gsa.gov/dsic/category/open-opportunities/) for projects to highligh

First draft of [Learn More](https://hackpad.com/Learn-More-rFFMnBbypjK) page had way too many words, and I really like the alternate suggestion of a long page, but there may be some words in there that would be useful.

**Comment by ultrasaurus** [comment]
art for the home page is here:  https://github.com/18F/midas-open-opportunities/pull/77

**Comment by ultrasaurus** [comment]
closed accidentally, will update on staging server so @LisaLNelson can review before we close

**Comment by LisaLNelson** [comment]
accept
