### ISSUE TITLE
As a visitor, I would like to see images that convey something about the task

### ISSUE THREAD

**Issue by LisaLNelson** [18F/midas-open-opportunities#32]
I would like to have an image automatically pop up for each type of task we publish.  Right now when we post a new tapa task the image of a tapas plate appears, when we post a new 20% task there is  an image of a pie cut in six pieces that goes up with it and when we publish an agency rep task (50% or more time) goes up we post a photo of arms and hands coming together. 

In addition, when a task is taken we change the photo to show the tapa, pie and arms with a closed through it. Here's an example:

Open tapas image: http://gsablogs.gsa.gov/dsic/2014/10/27/who-to-follow-on-twitter-kids-gov-wants-to-know/
Closed tapas image: http://gsablogs.gsa.gov/dsic/2014/09/30/task-for-video-script-writer/

We don't distinguish assigned from completed because the purpose of the image is to let people know what is available.  So we just use closed.

We have images we use but am happy to consider others.

**Comment by dhcole** [comment]
Haven't heard this come up recently, but CCing @GailSwanson to think about when we redesign this page.

**Comment by GailSwanson** [comment]
Thanks Dave,
I'll add it to the list of considerations for the platform's visual language.
