### ISSUE TITLE
As an admin, I would like to see better estimated time required, time commitment & deadline

### ISSUE THREAD

**Issue by LisaLNelson** [18F/midas-open-opportunities#35]
The info that is currently up is confusing for us.  Please change to reflect what we have. For tapas it can be a drop down so that the tapa user only sees the amount of time we expect his task to take.

![open opp form](https://cloud.githubusercontent.com/assets/9039852/4927054/71c987b4-6538-11e4-99d2-8196c56bb5e8.JPG)

What kind of opportunity is this? *
 Tapas 
 20 percent 
 Agency Rep

FOR TAPAS ONLY: How long do you expect the task to take?
 a few minutes to 1 hour
 up to 2 hours
 2-4 hours
 4-8 hours
 8-16 hours
 16-24 hours
 24-40 hours

What is the deadline for the volunteer to submit the completed project? *
 Ongoing
 One week after accepting the task
 Other:

**Comment by ultrasaurus** [comment]
popup menus for Open Opportunities:

will require:
a few minutes to 1 hour
up to 2 hours
2-4 hours
4-8 hours
8-16 hours
16-24 hours
24-40 hours]

must be complete within:  [1 week, 1 month, 3 months, 6 months]

**Comment by ultrasaurus** [comment]
proposed design:
![image](https://cloud.githubusercontent.com/assets/41906/6337975/4e8e6e62-bb60-11e4-9d33-36ab5c1a7bf6.png)

**Comment by ultrasaurus** [comment]
We're thinking of changing the language around "Tapas" / "20%"  so let's checking with @LisaLNelson before actually implementing this

**Comment by ultrasaurus** [comment]
Change to:
* Quick
* On-going

**Comment by ultrasaurus** [comment]
combining with MIdas issue:   https://github.com/18F/midas/issues/290
