### ISSUE TITLE
As an admin or task creator I need to be able to edit the skills 

### ISSUE THREAD

**Issue by LisaLNelson** [18F/midas-open-opportunities#44]
When I need to remove one of the skills there is not way for me to remove them.

**Comment by dhcole** [comment]
Clicking the "X" next to a skill on the task edit page removes the still.

<img width="536" alt="screen shot 2015-08-10 at 6 04 10 pm" src="https://cloud.githubusercontent.com/assets/170641/9185488/47ad6482-3f8a-11e5-9dce-b9bb0ee52b4f.png">
