### ISSUE TITLE
As a user, I should see a clear way to participate in a general discussion

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas-open-opportunities#45]
Right now there is no link here:  https://midas.18f.us/projects/4
We could change the title / info on that page if it made sense to
eventually we want this to replace the LinkedIn group

**Comment by dhcole** [comment]
@ultrasaurus is this still actionable? I haven't heard this come up recently.

**Comment by ultrasaurus** [comment]
@dhcole we definitely want a place for feedback -- not sure this is the right place.  I would leave this closed and prioritize having an email address that goes to a group or user voice or something

**Comment by dhcole** [comment]
:+1: tracking that here: https://github.com/18F/midas/issues/920
