### ISSUE TITLE
As a task creator, I should know that I am entering the title of my Opportunity in the first entry box

### ISSUE THREAD

**Issue by jpgsa** [18F/midas-open-opportunities#48]
Hi!

I just submitted a task. Great overall experience! 

One thought. When I entered my task, I found the phrase "What problem are you trying to solve" confusing the first cell. I didn't know I was entering the title there. Maybe you can create language to make it more clear that what you say there will be the title of the task. 

Overall, I didn't have any other issues. Keep up the good work!

**Comment by dhcole** [comment]
This is done now.
