### ISSUE TITLE
As an admin, I should get every notification

### ISSUE THREAD

**Issue by LisaLNelson** [18F/midas-open-opportunities#53]
We should make this configurable, since it will only make sense in early stage of the project

This is something we may turn off down the road but for now everytime someone expresses interest in a task I need to be notified. I think the same email that goes to the task creator can come to me.

**Comment by ultrasaurus** [comment]
https://github.com/18F/midas/issues/487

**Comment by ultrasaurus** [comment]
this is on midas-staging.gsa.gov

**Comment by LisaLNelson** [comment]
accept - tested on staging

**Comment by ultrasaurus** [comment]
FYI: was configured on production last week and moved to config for automated server today  https://github.com/18F/cloud-cutter/commit/0f47bb64527dc06b3a6af926874b5bb4b8b28f6e
