### ISSUE TITLE
As task creator, when someone signs up for my task I need to see their name in addition to their email address.

### ISSUE THREAD

**Issue by LisaLNelson** [18F/midas-open-opportunities#54]
The email address alone is not enough as it often does not include the full name of the person.

**Comment by ultrasaurus** [comment]
That happens when their profile isn't fllled in -- there are a few ways to approach this...

**Comment by ultrasaurus** [comment]
This will be fixed for future signups with https://github.com/18F/midas/pull/505

**Comment by LisaLNelson** [comment]
accept

**Comment by ultrasaurus** [comment]
for past users, we'll export the list of users w/o names filled in and Lisa will send them a note
