### ISSUE TITLE
As an admin, I should see a task dashboard

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas-open-opportunities#59]
List of Tasks  
* Open (#)
* Open with Sign-ups (#)  (someone has clicked “I’m in”)
* Assigned  (# 25-30)
* Completed  (#)

for each:
* Task Name (link),  Owner, Participants
* like: Kids.gov Twitter, Judy Smith => Bob Jones, Betty Rubble

**Comment by dhcole** [comment]
Ready with next deployment
