### ISSUE TITLE
Users are signing up without email addresses

### ISSUE THREAD

**Issue by dhcole** [18F/midas-open-opportunities#60]
See user 100. Needs research to figure out why.

**Comment by dhcole** [comment]
Look into user 102 as well. Looks like the email validation is failing to create a userEmail model.

Also, 101 is missing an email address.

**Comment by ultrasaurus** [comment]
I think they actually DO have email addresses, they just aren't showing up in the admin dashboard.  If you go to the numbered profile, you can see:  https://midas.18f.us/profile/101  (Dannielle actually has two email addresses. Since we're only using the first one, we should only show that one.

**Comment by dhcole** [comment]
Yes, the issue looks like somehow users are signing up but their email address is not getting saved as their user names. We can fix this for existing users with a script to take their most recent email and set it to their user name. But... we need to figure out why this happens in the first place.

**Comment by dhcole** [comment]
Ok, I think I found it. When you add or change your photo, it's clearing your user name (which is your email address). The email address is still saved in a separate table. The fix requires:

- [ ] Fix bug the removes user name
- [ ] Fill in missing user names with most recent email address
