### ISSUE TITLE
As a task creator, when I submit a task it should be in draft state...

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas-open-opportunities#61]
This depends on 

https://github.com/18F/midas/issues/465 When I submit a new opportunity, I should be able to save as draft..

https://github.com/18F/midas/issues/467 As a task creator, I should be able to see draft tasks in "card" view

https://github.com/18F/midas/issues/508 As a task creator, when I submit a task it should be in draft state...

**Comment by dhcole** [comment]
Last steps here are to set up the infrastructure. @ultrasaurus would you mind reviewing / testing these?

- https://github.com/18F/cloud-cutter/pull/36
- https://github.com/18F/midas-cookbook/pull/12

**Comment by ultrasaurus** [comment]
Leaving this open until we finish up the remaining related UI:
* https://github.com/18F/midas/issues/536
* https://github.com/18F/midas/issues/537
