### ISSUE TITLE
error on production server

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas-open-opportunities#72]
seems like Lisa may have been kicked off server this morning, I didn't see a specific error that would have caused that, but I did find a bunch of other errors in the log (from Wed & Fri last week, not from today) -- so it seems like something else, but still worth investigating:
```
res.notFound() :: When attempting to render error page view, an error occured (sending JSON instead).  Details:  ReferenceError: /var/www/midas/views/layout.ejs:9

    7|     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

    8|

 >> 9|     <title><%- systemName %></title>

    10|

    11|     <!-- <script type="text/javascript" src="/js/vendor/sails/socket.io.js"></script> -->

    12|     <!-- then beef it up with some convenience logic for talking to Sails.js -->



systemName is not defined

    at eval (eval at <anonymous> (/var/www/midas/node_modules/ejs/lib/ejs.js:1:0), <anonymous>:29:325)

    at eval (eval at <anonymous> (/var/www/midas/node_modules/ejs/lib/ejs.js:1:0), <anonymous>:29:5501)
```

**Comment by dhcole** [comment]
This is a harmless error message that just shows that Sails isn't able to render the layout template for HTTP errors and instead sends results as JSON. https://github.com/18F/midas/issues/593 Avoids this message altogether.
