### ISSUE TITLE
Opportunity complete email should include survey prompt

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas-open-opportunities#76]
(Email sent once the Task Creator has marked the Opportunity complete)

To: Participant
CC: Task Creator 
Subject Line: [Task name] is complete — thank you!  

Hi [user’s name],

Congrats! You’ve successfully completed “[task name here].” Your profile has been updated to reflect your achievement.

We at Open Opportunities are always looking for ways to make our program better. Please take a moment to complete this quick survey — your feedback will help us continue to improve your experience.

Thanks again,

The Open Opportunities Team

**Comment by ultrasaurus** [comment]
@LisaLNelson -- pls let us know the URL for the survey

**Comment by dhcole** [comment]
Tracking here: https://github.com/18F/midas/issues/580
