### ISSUE TITLE
As a member, I should be able to add my agency...

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas-open-opportunities#79]
We need to add...
* Office of Science and Technology Policy (OSTP)
* Executive Office of the President (EOP)

**Comment by ultrasaurus** [comment]
@dhcole I'll add notes about how to do this, if I don't have time to do today

**Comment by ultrasaurus** [comment]
@dhcole sorry, not to get to this.  See "Bulk import of tag data"  https://github.com/18F/midas/blob/devel/CONFIG.md

**Comment by dhcole** [comment]
Added to production DB.
