### ISSUE TITLE
As an admin, I should be able to get an exact count of users on the platform.

### ISSUE THREAD

**Issue by LisaLNelson** [18F/midas-open-opportunities#80]
Right now the list of users is filled with test participants, a few non-feds and duplicate users (bug?). I need the ability to report the correct number of users on the platform when management asks.

A great fix for me would be if the count would auto correct when someone's account is disabled.

**Comment by ultrasaurus** [comment]
Great minds think alike!  This is actually what we did a while back... if you disable users, they don't contribute to the user count on the main summary dashboard screen.  We used to have 142 users -- I disable 10 of the kristin users and now we have 132:

![image](https://cloud.githubusercontent.com/assets/41906/6261617/287e11b2-b7a7-11e4-9a6d-a41141d5c657.png)

**Comment by LisaLNelson** [comment]
accept
