### ISSUE TITLE
DAP script tag points to a 404

### ISSUE THREAD

**Issue by tdlowden** [18F/midas-open-opportunities#85]
The tag calls a cloudfront url, which is a 404, and then directs to the analytics.usa.gov repo to file an issue.

**Comment by ultrasaurus** [comment]
@tdlowden thanks for letting us know. It worked when we set it up, but something must have changed.  Will look into it.

**Comment by ultrasaurus** [comment]
we should use:  https://analytics.usa.gov/dap/dap.min.js

**Comment by dhcole** [comment]
Just needs an update here: https://github.com/18F/midas-open-opportunities/blob/master/config/settings/analytics.js
